common_metadata = ['id', 'address', 'run', 'plate', 'dev_or_prod', 'exp_workflow_barcode', 'exp_workflow_name', 'proj_barcode', 'proj_name', 'ctrl_type', 'exp_condition', 'enzyme_barcode', 'sequence', 'hamming', 'mutations', 'reference_enzyme', 'enzyme_concentration', 'enzyme_unit', 'enzyme_class', 'sequence_qc']
enzyme_metadata = ['enzyme_barcode', 'sequence', 'hamming', 'mutations', 'reference_enzyme', 'enzyme_concentration', 'enzyme_unit', 'enzyme_class', 'sequence_qc']
library_metadata = ["seed_address", "seed_address_alphanumeric", "seed_plate", "main_plate", "rxn_plate", "library_barcode", "library_ref", "library_description"]
plate_time_metadata = ['seed_plate_time', 'main_plate_time', 'rxn_plate_time', 'plate_time']
pelletqc_metadata = ['pellet_OD', 'pellet_detected', 'pellet_area', 'pellet_intensity']
conversion_ee_metrics = ['measured_conversion_(r)', 'measured_conversion_(+)', 'measured_conversion_(-)', 
                         'measured_enantiomeric_excess_(+over-)', 'measured_enantiomeric_ratio_(+over-)']
############################
####### SEQUENCING #########
############################

enzyme_metrics = ['enzyme_barcode', 'sequence', 'hamming', 'mutations', 'enzyme_class', 'reference_enzyme', 'sequence_qc', 'enzyme_concentration', 'enzyme_unit']

###############################
######### PELLETQC ############
###############################

pelletqc_columns = ['plate', 'address', 'exp_condition', 'ctrl_type', 'x', 'y', 'ideal_centroidYX', 'centroidYX', 'abspos_err', 'w2hratio', 'pellet_area', 'pellet_diameter', 'pellet_intensity', 'pellet_intensity_std', 'pellet_bkgd_intensity', 'pellet_detected', 'pellet_OD_predicted', 'pellet_OD_measured']

############################
######## ANALYTICS #########
############################

combi_analytics_metrics = [
    'id',
    'exp_workflow_barcode',
    'exp_workflow_name',
    'proj_barcode',
    'proj_name',
    'maldi_run',
    'lcms_C18_run',
    'lcms_chiral_run',
    'maldi_plate_(r)',
    'maldi_address_(r)',
    'lcms_plate_(r)',
    'lcms_address_(r)',
    'source_plate_(r)',
    'source_address_(r)',
    'maldi_plate_(+)',
    'maldi_address_(+)',
    'lcms_plate_(+)',
    'lcms_address_(+)',
    'source_plate_(+)',
    'source_address_(+)',
    'maldi_plate_(-)',
    'maldi_address_(-)',
    'lcms_plate_(-)',
    'lcms_address_(-)',
    'source_plate_(-)',
    'source_address_(-)',
    'ctrl_type',
    'exp_condition',
    'enzyme_barcode',
    'sequence',
    'mutations',
    'hamming',
    'reference_enzyme',
    'substrate_barcode_(r)',
    'substrate_barcode_(+)',
    'substrate_barcode_(-)',
    'substrate_smiles_(r)',
    'substrate_smiles_(+)',
    'substrate_smiles_(-)',
    'substrate_concentration_(r)',
    'substrate_concentration_(+)',
    'substrate_concentration_(-)',
    'predicted_binary_score_(r)',
    'predicted_nonbinary_score_(r)',
    'measured_nonbinary_score_(r)',
    'measured_nonbinary_sum_(r)',
    'measured_conversion_(r)',
    'predicted_binary_score_variance_(r)',
    'predicted_nonbinary_score_variance_(r)',
    'predicted_binary_score_(+)',
    'predicted_nonbinary_score_(+)',
    'measured_nonbinary_score_(+)',
    'measured_conversion_(+)',
    'predicted_binary_score_variance_(+)',
    'predicted_nonbinary_score_variance_(+)',
    'predicted_binary_score_(-)',
    'predicted_nonbinary_score_(-)',
    'measured_nonbinary_score_(-)',
    'measured_conversion_(-)',
    'predicted_binary_score_variance_(-)',
    'predicted_nonbinary_score_variance_(-)',
    'measured_enantiomeric_excess_(+over-)',
    'predicted_enantiomeric_excess_(+over-)',
    'measured_enantiomeric_ratio_(+over-)',
    'predicted_enantiomeric_ratio_(+over-)',
    ] + ['seed_address', 'seed_address_alphanumeric', 'seed_plate', 'library_barcode', 'library_ref', 'library_description', 'seed_plate_time'] + pelletqc_metadata


enzyme_analytics_metrics = [
    'exp_workflow_barcode',
    'exp_workflow_name',
    'proj_barcode',
    'proj_name',
    'maldi_run',
    'lcms_C18_run',
    'lcms_chiral_run',
    'maldi_plate_(r)',
    'maldi_address_(r)',
    'lcms_plate_(r)',
    'lcms_address_(r)',
    'source_plate_(r)',
    'source_address_(r)',
    'maldi_plate_(+)',
    'maldi_address_(+)',
    'lcms_plate_(+)',
    'lcms_address_(+)',
    'source_plate_(+)',
    'source_address_(+)',
    'maldi_plate_(-)',
    'maldi_address_(-)',
    'lcms_plate_(-)',
    'lcms_address_(-)',
    'source_plate_(-)',
    'source_address_(-)',
    'ctrl_type',
    'enzyme_barcode',
    'sequence',
    'mutations',
    'hamming',
    'reference_enzyme',
    'substrate_barcode_(r)',
    'substrate_barcode_(+)',
    'substrate_barcode_(-)',
    'substrate_smiles_(r)',
    'substrate_smiles_(+)',
    'substrate_smiles_(-)',
    'substrate_concentration_(r)',
    'substrate_concentration_(+)',
    'substrate_concentration_(-)',
    'predicted_binary_score_(r)',
    'predicted_nonbinary_score_(r)',
    'measured_nonbinary_score_(r)',
    'measured_conversion_(r)',
    'predicted_binary_score_variance_(r)',
    'predicted_nonbinary_score_variance_(r)',
    'predicted_binary_score_(+)',
    'predicted_nonbinary_score_(+)',
    'measured_nonbinary_score_(+)',
    'measured_conversion_(+)',
    'predicted_binary_score_variance_(+)',
    'predicted_nonbinary_score_variance_(+)',
    'predicted_binary_score_(-)',
    'predicted_nonbinary_score_(-)',
    'measured_nonbinary_score_(-)',
    'measured_conversion_(-)',
    'predicted_binary_score_variance_(-)',
    'predicted_nonbinary_score_variance_(-)',
    'measured_enantiomeric_excess_(+over-)',
    'predicted_enantiomeric_excess_(+over-)',
    'measured_enantiomeric_ratio_(+over-)',
    'predicted_enantiomeric_ratio_(+over-)',
    ] + ['seed_address', 'seed_address_alphanumeric', 'seed_plate', 'library_barcode', 'library_ref', 'library_description', 'seed_plate_time'] + pelletqc_metadata

maldi_plate_analytics_metrics = [
    'plate',
    'run',
    'dev_or_prod',
    'proj_name',
    'proj_barcode',
    'exp_workflow_name',
    'exp_workflow_barcode',
    'expression_condition', 
    'screen_condition', 
    'acq_condition',
    'num_mtx_ctrl',
    'pk_mtx_172_raw_mean',
    'pk_mtx_172_raw_median',
    'pk_mtx_172_raw_stdev',
    'pk_mtx_172_raw_iqr',
    'pk_mtx_190_raw_mean',
    'pk_mtx_190_raw_median',
    'pk_mtx_190_raw_stdev',
    'pk_mtx_190_raw_iqr',
    'pk_mtx_379_raw_mean',
    'pk_mtx_379_raw_median',
    'pk_mtx_379_raw_stdev',
    'pk_mtx_379_raw_iqr',
    'num_neg_ctrl',
    'neg_ctrl_enzyme_barcode',
    'neg_ctrl_substrate_barcode',
    'neg_ctrl_fpr',
    'neg_ctrl_sub_stdz_379_mean',
    'neg_ctrl_sub_stdz_379_median',
    'neg_ctrl_sub_stdz_379_stdev',
    'neg_ctrl_sub_stdz_379_iqr',
    'neg_ctrl_prod_stdz_379_mean',
    'neg_ctrl_prod_stdz_379_median',
    'neg_ctrl_prod_stdz_379_stdev',
    'neg_ctrl_prod_stdz_379_iqr',
    'neg_ctrl_ptr_mean',
    'neg_ctrl_ptr_median',
    'neg_ctrl_ptr_stdev',
    'neg_ctrl_ptr_iqr',
    'neg_ctrl_tstat_sub_stdz_379_mean',
    'neg_ctrl_tstat_sub_stdz_379_median',
    'neg_ctrl_tstat_sub_stdz_379_stdev',
    'neg_ctrl_tstat_sub_stdz_379_iqr',
    'neg_ctrl_tstat_prod_stdz_379_mean',
    'neg_ctrl_tstat_prod_stdz_379_median',
    'neg_ctrl_tstat_prod_stdz_379_stdev',
    'neg_ctrl_tstat_prod_stdz_379_iqr',
    'neg_ctrl_tstat_ptr_mean',
    'neg_ctrl_tstat_ptr_median',
    'neg_ctrl_tstat_ptr_stdev',
    'neg_ctrl_tstat_ptr_iqr',
    'num_pos_ctrl',
    'pos_ctrl_enzyme_barcode',
    'pos_ctrl_substrate_barcode',
    'pos_ctrl_fnr',
    'pos_ctrl_sub_stdz_379_mean',
    'pos_ctrl_sub_stdz_379_median',
    'pos_ctrl_sub_stdz_379_stdev',
    'pos_ctrl_sub_stdz_379_iqr',
    'pos_ctrl_prod_stdz_379_mean',
    'pos_ctrl_prod_stdz_379_median',
    'pos_ctrl_prod_stdz_379_stdev',
    'pos_ctrl_prod_stdz_379_iqr',
    'pos_ctrl_ptr_mean',
    'pos_ctrl_ptr_median',
    'pos_ctrl_ptr_stdev',
    'pos_ctrl_ptr_iqr',
    'pos_ctrl_tstat_sub_stdz_379_mean',
    'pos_ctrl_tstat_sub_stdz_379_median',
    'pos_ctrl_tstat_sub_stdz_379_stdev',
    'pos_ctrl_tstat_sub_stdz_379_iqr',
    'pos_ctrl_tstat_prod_stdz_379_mean',
    'pos_ctrl_tstat_prod_stdz_379_median',
    'pos_ctrl_tstat_prod_stdz_379_stdev',
    'pos_ctrl_tstat_prod_stdz_379_iqr',
    'pos_ctrl_tstat_ptr_mean',
    'pos_ctrl_tstat_ptr_median',
    'pos_ctrl_tstat_ptr_stdev',
    'pos_ctrl_tstat_ptr_iqr',
    'num_exp_ctrl',
    'num_exp_variants',
    'exp_ctrl_enzyme_barcode',
    'exp_ctrl_substrate_barcode',
    'exp_ctrl_hit_rate',
    'exp_ctrl_sub_stdz_379_mean',
    'exp_ctrl_sub_stdz_379_median',
    'exp_ctrl_sub_stdz_379_stdev',
    'exp_ctrl_sub_stdz_379_iqr',
    'exp_ctrl_prod_stdz_379_mean',
    'exp_ctrl_prod_stdz_379_median',
    'exp_ctrl_prod_stdz_379_stdev',
    'exp_ctrl_prod_stdz_379_iqr',
    'exp_ctrl_ptr_mean',
    'exp_ctrl_ptr_median',
    'exp_ctrl_ptr_stdev',
    'exp_ctrl_ptr_iqr',
    'exp_ctrl_tstat_sub_stdz_379_mean',
    'exp_ctrl_tstat_sub_stdz_379_median',
    'exp_ctrl_tstat_sub_stdz_379_stdev',
    'exp_ctrl_tstat_sub_stdz_379_iqr',
    'exp_ctrl_tstat_prod_stdz_379_mean',
    'exp_ctrl_tstat_prod_stdz_379_median',
    'exp_ctrl_tstat_prod_stdz_379_stdev',
    'exp_ctrl_tstat_prod_stdz_379_iqr',
    'exp_ctrl_tstat_ptr_mean',
    'exp_ctrl_tstat_ptr_median',
    'exp_ctrl_tstat_ptr_stdev',
    'exp_ctrl_tstat_ptr_iqr',
]


